# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentlistfile',
            name='datafile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='markfile',
            name='datafile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentlistfile',
            name='datafile',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='talistfile',
            name='datafile',
            field=models.FileField(upload_to=''),
        ),
    ]
